# Generated by Django 6.1 on 2026-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('email', 'Email'), ('phone', 'Phone')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
