# Generated by Django 6.1 on 2026-08-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_socialmedia_platform_alter_socialmedia_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='url',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
