# Generated by Django 6.1 on 2026-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_user_alter_skill_name_skill_unique_user_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
